name: Nginx Config Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nginx
        run: |
          sudo apt update
          sudo apt install -y nginx

      - name: Copy Config
        run: |
          sudo cp nginx/nginx.conf /etc/nginx/nginx.conf

      - name: Test Nginx Config
        run: |
          sudo nginx -t
